/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/fiil/": {
    get: {
      parameters: {
        query: {
          value?: string;
        };
      };
      responses: {
        /** Successful Response */
        200: {
          content: {
            "application/json": components["schemas"]["def-0"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /**
     * countSchema
     * @description something
     */
    "def-0": {
      count?: number;
      value?: string;
    };
  };
}

export interface operations {}

export interface external {}
